<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>



<form action="#" id="mass_products">
<?php
	$_productCollection=$this->getLoadedProductCollection();
	$_collectionSize = $_productCollection->count();
?>

<?php if(!$_collectionSize): ?><?php
	 if ($tmpHtml = $this->getChildHtml('block_category_above_empty_collection')) {
		?><div class="block_category_above_empty_collection std"><?php echo $tmpHtml; ?></div><?php
	 } else {
		?><p class="note-msg empty-catalog"><?php echo $this->__('There are no products matching the selection.') ?></p><?php
	 }
?><?php else: ?>

<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('wsu_themecontrol');
	$helpLabels = $this->helper('wsu_themecontrol/labels');
	$helpTemplate = $this->helper('wsu_themecontrol/template');
	$helpImg = $this->helper('wsu_wsu/image');
	
	//Default image size
	$imgWidth = 340;
	$imgHeight = 0;
	
	//Aspect ratio settings
	if ($theme->getCfg('category/aspect_ratio')) {
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio
	}
	//Hide toolbar
	$hideToolbar = true;
	if ($this->getHideToolbar()) {
		$hideToolbar = true;
	}
?>

<div class="category-products">
	<?php
		//Get list configuration array
		$lc = $theme->getCfgGroup('category_list');
		
		//List classes
		$listClasses = '';
		if ($lc['hover_effect']) {
			$listClasses = ' hover-effect';
		}

	?>

	<?php $_iterator = 0; ?>
	<ul class="products-list<?php if($listClasses) echo $listClasses; ?>" id="products-list">
	<?php foreach ($_productCollection as $_product): ?>
			<?php 
				$productType=$_product->getTypeID();
				$pID=$_product->getId();
				$product = Mage::getModel('catalog/product');
				$product = Mage::getModel("catalog/product")->load($pID);
				$eventStart = $product->getEventstartdate();
				$eventEnd = $product->getEventenddate();
				$FoodOptions = $product->getFoodOptions();
				$HasAccessValidation = $product->getHasAccessValidation();
				$AccessCode = $product->getAccessCode();
				
				
				
			?>
	
		<li class="mass_item item row margin-left <?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" data-product_id="<?=$pID?>">
			<input type="hidden" value="<?=$pID?>" name="products[]"/>
			<input type="checkbox" name="goingToEvent"/>
			
			<?php if($HasAccessValidation): ?>
				<div class="validation_overlay">
					<div class="access_form">Enter Access Code<br/>
						<input type="text" class="full" data-valid="<?=$AccessCode?>"/>
					</div>
				</div>
			<?php endif; ?>

		
		
			
			<?php //Product Image ?>
			<div class="product-image-wrapper column one">
				<?php 
					$imgLable = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); 
				?>
				<img src="<?=$helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image');?>" alt="<?=$imgLable?>" width="100%"/>
			</div> <!-- end: product-image-wrapper -->
			
			<div class="product-data column two padded-left narrow">
				<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				<h2 class="product-name">
					<?=$_helper->productAttribute($_product, $_product->getName() , 'name')?>
				</h2>
				<div class="row halves">
					<div class="column">
						<?php if($eventStart!==$eventEnd):?>
							Starting at <?=date('l jS \of F Y h:i:s A',strtotime($eventStart));?>
							<br/>
							Till <?=date('l jS \of F Y h:i:s A',strtotime($eventEnd));?>
							<br/> 
						<?php else: ?>
							on <?=date('l jS \of F Y',strtotime($eventStart));?> at <?=date('h:i:s A',strtotime($eventStart));?>
						<?php endif; ?>
					</div>
					<div class="column padded-left narrow cart_action_area">
					
						<?php echo $this->getPriceHtml($_product, true) ?>
						
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?=$this->__('Attend') ?>" class="button btn-cart"><span><span><?=$this->__('Attend') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?=$this->__('Sorry, event is filled.') ?></span></p>
						<?php endif; ?>
					
					</div>
				</div>
			
				<?php //Product description ?>
				<div class="desc std">
					<?=$product->getDescription()?>
					<!--<a href="<?php echo $_product->getProductUrl() ?>" title="<?=$_productNameStripped ?>" class="link-learn"><?=$this->__('Learn More') ?></a>-->
				</div>					
					
				<input type="hidden" value="1" name="product[<?=$pID?>][qty]">
				
			</div>
				<div class="row halves attendence_block">
					<div class="column">
						<h4>Your Event Options:</h4>
						<?php if($FoodOptions>0): ?>
							<span>Meal Choice:</span><br/>
							<select name="product[<?=$pID?>][options][meal]">
								<option>Beef</option>
								<option>Fish</option>
								<option>Vegetarian</option>
							</select><br/>
							<span>Dietary Requests:</span><br/>
							<input type="text"  name="product[<?=$pID?>][options][dietary]" class="full"/>
							<br/>
						<?php endif; ?>
						<span>Mobility Requests:</span><br>
						<input type="text"  name="product[<?=$pID?>][options][mobility]" class="full"/>
						<br/>
					</div>
					<div class="column padded-left narrow">
					<?php		
						
						$AllowGuest = $product->getAllowGuests();
						

						if($AllowGuest>0){
							$GuestQty = $product->getGuestCost();
							//$GuestLimit = $product->getGuestLimit();
							$GuestLimit = $product->getAttributeText("guest_limit");
							?>
							
							<ul class="guest_blocks" data-limit="<?=$GuestLimit?>">
								<li><a href="#" class="add_guest  spine-button"><i class="fa fa-plus"></i> Add Guest</a><a href="#" class="copy_guest  spine-button"><i class="fa fa-clipboard" title="Copy guests from another event."></i></a></li>
								<li class="guest_block template">
									<a href="#" class="remove_guest spine-button"><span class="fa-stack fa-sm">
									  <i class="fa fa-circle fa-stack-2x"></i>
									  <i class="fa fa-times fa-stack-1x fa-inverse"></i>
									</span></a>
									<span class="blockHeader">Guest <i class="count">{%d%}</i></span><br/>
									<div class="row halves padded-bottom short">
										<div class="column">
											<span>First Name:</span><input type="text" name="product[<?=$pID?>][options][guest][{%d%}][firstName]" class="full"/>
										</div>
										<div class="column padded-left narrow">
											<span>Last Name:</span><input type="text"  name="product[<?=$pID?>][options][guest][{%d%}][lastName]" class="full"/>
										</div>
									</div>
									<?php if($FoodOptions>0): ?>
									<div class="row side-left padded-bottom short">
										<div class="column">
											<span>Meal Choice:</span><br/>
											<select name="product[<?=$pID?>][options][guest][{%d%}][meal]">
												<option>Beef</option>
												<option>Fish</option>
												<option>Vegetarian</option>
											</select>
										</div>
										<div class="column padded-left narrow">
											<span>Dietary Requests:</span><input type="text"  name="product[<?=$pID?>][options][guest][{%d%}][dietary]" class="full"/>
										</div>
									</div>
									<?php endif; ?>
									
									<a href="#" class="add_guest  spine-button"><i class="fa fa-plus"></i> Add Guest </a>
								</li>
							
							
							</ul>
							
							
							<?php
						}
						 
					?>
						 <!--
					<?php
						$attVal = $product->getOptions();
						 
						$optStr = "";
						
						//var_dump($attVal);
						// loop through the options
						$i=0;
						foreach($attVal as $optionKey => $option) {
							$field=$option->getData();
							if($field['type']=="field"){
								if($i<1){
								$optStr .= "<a href='#' class='button add_guest' ><i class='fa fa-plus'></i>Additional Guest ($".money_format ( $option->getPrice() , 2 ).") </a>";
								}
								$optStr .= "<div class='guest_block' style='display:none;>";
								$optStr .= $option->getTitle().": ";
								$optStr .= "<input type='text' name='options[".$option->getId()."]' />";
								if($i>0 && $i < (count($attVal)-1)){
									$optStr .= "</br><a href='#' class='button add_guest' ><i class='fa fa-plus'></i>Add another Guest for an additional ".money_format ( $option->getPrice() , 2 )." </a>";
								}
								$optStr .= "</div>";
								$i++;
							}else{
								//$optStr .= "<br/>";
								 
								//$optStr .= $optionVal->getTitle().": ";
								 
								$optStr .= "<select style='display:block; clear:both;' name='options[".$option->getId()."]'>";
								 
								foreach($option->getValues() as $valuesKey => $valuesVal) {
									$optStr .= "<option value='".$valuesVal->getId()."'>".$valuesVal->getTitle()."</option>";
								}
								$optStr .= "</select>";
							}
						}
						 
						echo($optStr );
						
					?>-->
					</div>
				</div>
		</li>
	<?php endforeach; ?>
	</ul>
	<a href="#" id="check_out_products" class="spine-button">Check out</a>
</div>
<?php endif; ?>
</form>


<script type="text/javascript">
(function($){
	"use strict";
	
	var formatter = new Intl.NumberFormat('en-US', {
	  style: 'currency',
	  currency: 'USD',
	  minimumFractionDigits: 2,
	});
	
	$(document).ready(function(){
		function popup_message(html_message,clean){
			if(typeof(clean)==="undefined"){
				clean=false;
			}
			if($("#mess").length<=0){
				$('body').append('<div id="mess">');
			}
			$("#mess").html( (typeof html_message === 'string' || html_message instanceof String) ? html_message : html_message.html() );
			$( "#mess" ).dialog({
				autoOpen: true,
				resizable: false,
				width: 350,
				minHeight: 25,
				modal: true,
				draggable : false,
				create:function(){
					if(clean){
						$('.ui-dialog-titlebar').remove();
						$(".ui-dialog-buttonpane").remove();
					}
					$('body').css({overflow:"hidden"});
				},
				buttons:{
					Ok:function(){
						$( this ).dialog( "close" );
					}
				},
				close: function() {
					$('body').css({overflow:"auto"});
					$( "#mess" ).dialog( "destroy" );
					$( "#mess" ).remove();
				}
			});
		}
				
		$.each($(".regular-price"), function(){
			$(this).data("price",$(this).text().replace('$',''));
		});
		
		function int_addGuest(){
			$('.add_guest').off().on('click',function(e){
				
				e.preventDefault();
				e.stopPropagation();
				
				var _block = $(this).closest(".item");
				
				_block.find(".template").clone().appendTo(_block.find('.guest_blocks')).removeClass("template");
				var guest_count = _block.find('.guest_block:not(.template)').length;
				var block_content = _block.find('.guest_block').last().html().toString();
				//alert(block_content);
				_block.find('.guest_block').last().html( block_content.replace(/{%d%}/gim, guest_count) );
				$(this).hide();
				_block.find(".price").text(  formatter.format( _block.find(".regular-price").data("price")*( guest_count+1) ) );
				_block.find('[name$="[qty]"]').val(guest_count+1);
				var limit = _block.find('.guest_blocks').data('limit');
				if(limit=="unlimited" || limit<guest_count){
					int_addGuest();
				}else{
					_block.find('.add_guest').hide();
				}
				int_removeGuest();
			});
		}

		function int_removeGuest(){
			$('.remove_guest').off().on('click',function(e){
				e.preventDefault();
				e.stopPropagation();
				
				var _block = $(this).closest(".item");
				
				$(this).closest(".guest_block").remove();
				
				$.each(_block.find('.guest_block:not(.template)'), function(i,v){
					var adj_i =i+1;
					$(this).find(".count").text( adj_i );
					$(this).html( $(this).html().toString().replace(/\[guest\]\[\d+?\]/gmi, "guest["+adj_i+"]") );
				});
				var guest_count = _block.find('.guest_block:not(.template)').length;
				_block.find(".price").text( formatter.format( _block.find(".regular-price").data("price")*( guest_count+1) ) );
				_block.find('[name$="[qty]"]').val(guest_count+1);
				/*if(guest_count<=0){
					_block.find('.add_guest').show();
				}else{
					_block.find('.add_guest').last().show();
				}*/_block.find('.add_guest').last().show();
				int_addGuest();
				int_removeGuest();
			});
		}

		$.fn.int_guest_display = function() {
			$.each($(this),function(){
				$(this).find('.guest_blocks').show();
				
				if($('.guest_block').is($(':visible')) && !($(this).has( $('.guest_block').is($(':visible'))) )  ){
					$(this).find('.copy_guest').addClass('can_copy');
					$('.can_copy').on('click',function(){
						//$('')
					});
				}
			});
		};
		$.fn.destroy_guest_display = function() {
			$.each($(this),function(){
				var _block =$(this);
				
				var guest_count = 0;
				
				_block.find(".guest_block:not(.template)").remove();
				_block.find(".price").text(  formatter.format( _block.find(".regular-price").data("price")*( guest_count+1) ) );
				_block.find('[name$="[qty]"]').val(guest_count+1);
				
				_block.find('.guest_blocks').hide();
				_block.find('.add_guest').show();
				_block.find('.copy_guest').removeClass('can_copy');
			});
		};

		$.fn.int_access_validation = function() {
			var _block =$(this);
			if( _block.is($('.passed')) ){
				return true;	
			}else{
				_block.addClass('active');
				_block.find('.access_form input').focus();
				_block.find('.access_form input').on('keyup',function(){
					if($(this).val() === $(this).data('valid')){
						_block.removeClass('active');
						_block.addClass('passed');
						_block.closest('.mass_item').find('.button.btn-cart').trigger('click');
					}
				});
				return false;
			}
		};

		$('.button.btn-cart').off().on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			var but = $(this);
			var tar = but.closest('.mass_item').find('[name="goingToEvent"]');
			if( tar.is($(":checked")) ){
				but.closest('.mass_item').destroy_guest_display();
				tar.attr('checked',false);
				but.html('<span><span>Attend</span></span>');
				but.closest('.mass_item').removeClass('active_item');
			}else{
				if( but.closest('.mass_item').find('.validation_overlay').length<=0 || but.closest('.mass_item').find('.validation_overlay').int_access_validation()){
					tar.attr('checked',true);
					but.html('<span><span>Don\'t Attend</span></span>');
					but.closest('.mass_item').addClass('active_item');
					but.closest('.mass_item').int_guest_display();
					int_addGuest();
				}
			}
		});

		$('#check_out_products').on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			
			 
			
			
			var formData = $('#mass_products')
							.find('.mass_item.item:has([name="goingToEvent"]:checked) :input:not(.template > :input)')
							.serialize();
							
			popup_message("<h4><i class='fa fa-spinner fa-spin'></i> Processing</h4>",true);
			$.post('/cartajax/cartajax/add/?cartAjaxUsed=1',formData,function(data){
					var data_res = jQuery.parseJSON(data);
					console.log( data_res );
					if(data_res.status=="ERROR" || data_res.checkout==""){
						$( "#mess" ).dialog( "destroy" );
						$( "#mess" ).remove();
						popup_message("Issue with order"+data_res.message,false);
					}else{
						window.location = '/onepage/';
					}
			});
		});
		
		/*
		$('#check_out_products').on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			var data = {"cartAjaxUsed":1};
			var porducts = {};
			$.each($('.mass_item'),function(){
				var self = $(this);
				var pid = self.data('product_id');
				var pdata = {};
				$.each(self.find('input,select,textarea'),function(){
					pdata[$(this).attr('name')]=$(this).val();
				});
				porducts[pid]=pdata;
			});
			$.extend(data,{"items":porducts});
			popup_message("<h4><i class='fa fa-spinner fa-spin'></i> Processing</h4>",true);
			$.post('/cartajax/cartajax/add/',data,function(response){
					if(response.checkout!=""){
						window.location = '/onepage/';
					}else{
						$( "#mess" ).dialog( "destroy" );
						$( "#mess" ).remove();
						popup_message("Issue with order"+response.message,false);
					}
			});
		});
		*/
		
		
		
		
	});
})(jQuery);
</script>
















