<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
	$_productCollection=$this->getLoadedProductCollection();
	$_collectionSize = $_productCollection->count();
?>

<?php if(!$_collectionSize): ?><?php
	 if ($tmpHtml = $this->getChildHtml('block_category_above_empty_collection')) {
		?><div class="block_category_above_empty_collection std"><?php echo $tmpHtml; ?></div><?php
	 } else {
		?><p class="note-msg empty-catalog"><?php echo $this->__('There are no products matching the selection.') ?></p><?php
	 }
?><?php else: ?>

<?php
	$_helper = $this->helper('catalog/output');
	$theme = $this->helper('wsu_themecontrol');
	$helpLabels = $this->helper('wsu_themecontrol/labels');
	$helpTemplate = $this->helper('wsu_themecontrol/template');
	$helpImg = $this->helper('wsu_wsu/image');
	
	//Default image size
	$imgWidth = 295;
	$imgHeight = 295;
	
	//Aspect ratio settings
	if ($theme->getCfg('category/aspect_ratio')) {
		$imgHeight = 0; //Height will be computed automatically (based on width) to keep the aspect ratio
	}
	//Hide toolbar
	$hideToolbar = true;
	if ($this->getHideToolbar()) {
		$hideToolbar = true;
	}
?>

<div class="category-products padded">
	<?php
		//Get list configuration array
		$lc = $theme->getCfgGroup('category_list');
		
		//List classes
		$listClasses = '';
		if ($lc['hover_effect']) {
			$listClasses = ' hover-effect';
		}

	?>

	<?php $_iterator = 0; ?>
	<ul class="products-list<?php if($listClasses) echo $listClasses; ?>" id="products-list">
	<?php foreach ($_productCollection as $_product): ?>
			<?php 
				$productType=$_product->getTypeID();
				$product=Mage::getModel('catalog/product')->load($_product->getId());
				$eventStart = $product->getEventstartdate();
				$eventEnd = $product->getEventenddate();
			?>
	
		<li class="mass_item item row margin-left <?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>" data-product_id="<?=$_product->getId()?>">
			<input type="checkbox" value="" name="goingToEvent"/>
			<?php //Product Image ?>
			<div class="product-image-wrapper column one">
				<?php 
					$imgLable = $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); 
				?>
				<a href="<?=$_product->getProductUrl()?>" title="<?=$imgLable?>" class="product-image" style="max-width:<?=$imgWidth;?>px;">
					<img src="<?=$helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image');?>" alt="<?=$imgLable?>" width="100%"/>
				</a>
			</div> <!-- end: product-image-wrapper -->
			
			<div class="product-data column two padded-left narrow">
				<?php //Product description ?>
				<div class="product-shop">
					<div class="product-shop-inner">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?=$_product->getProductUrl()?>" title="<?=$_productNameStripped?>"><?=$_helper->productAttribute($_product, $_product->getName() , 'name')?></a></h2>
						
						<div class="desc std">
							Starting : <?=$eventStart?><br/>
							Ending : <?=$eventEnd?><br/> 
							<?=$_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?=$_productNameStripped ?>" class="link-learn"><?=$this->__('Learn More') ?></a>
						</div>
					</div>
				</div>
					
				<div class="right-column">
					<?php echo $this->getPriceHtml($_product, true) ?>
					
					<?php if($_product->isSaleable()): ?>
						<p><button type="button" title="<?=$this->__('Attend') ?>" class="button btn-cart"><span><span><?=$this->__('Attend') ?></span></span></button></p>
					<?php else: ?>
						<p class="availability out-of-stock"><span><?=$this->__('Sorry, event is filled.') ?></span></p>
					<?php endif; ?>
					
					
					<?php		
						$productSku = $_product->getSku();
						$product = Mage::getModel('catalog/product');
						$productId = $product->getIdBySku( $productSku );
						 
						$product = Mage::getModel("catalog/product")->load($productId);
						 
						$attVal = $product->getOptions();
						 
						$optStr = "";
						
						//var_dump($attVal);
						// loop through the options
						$i=0;
						foreach($attVal as $optionKey => $option) {
							$field=$option->getData();
							if($field['type']=="field"){
								if($i<1){
								$optStr .= "<a href='#' class='button add_guest' ><i class='fa fa-plus'></i>Additional Guest ($".money_format ( $option->getPrice() , 2 ).") </a>";
								}
								$optStr .= "<div class='guest_block' style='display:none;>";
								$optStr .= $option->getTitle().": ";
								$optStr .= "<input type='text' name='options[".$option->getId()."]' />";
								if($i>0 && $i < (count($attVal)-1)){
									$optStr .= "</br><a href='#' class='button add_guest' ><i class='fa fa-plus'></i>Add another Guest for an additional ".money_format ( $option->getPrice() , 2 )." </a>";
								}
								$optStr .= "</div>";
								$i++;
							}else{
								//$optStr .= "<br/>";
								 
								//$optStr .= $optionVal->getTitle().": ";
								 
								$optStr .= "<select style='display:block; clear:both;' name='options[".$option->getId()."]'>";
								 
								foreach($option->getValues() as $valuesKey => $valuesVal) {
									$optStr .= "<option value='".$valuesVal->getId()."'>".$valuesVal->getTitle()."</option>";
								}
								$optStr .= "</select>";
							}
						}
						 
						echo($optStr );
					?>
					
					
					

					
					
				</div>
			</div>
		</li>
	<?php endforeach; ?>
	</ul>
	<a href="#" id="check_out_products">Check out</a>
</div>
<?php endif; ?>



<script type="text/javascript">
(function($){
	"use strict";
	$(document).ready(function(){
		$('.add_guest').on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			$(this).closest('.guest_block').next('.guest_block').show();	
			$(this).hide();
		});

		$('.button.btn-cart').off().on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			$(this).closest('.mass_item').find('[name="goingToEvent"]').attr('checked',true);
			
		});



		$('#check_out_products').on('click',function(e){
			e.preventDefault();
			e.stopPropagation();
			var data = {"cartAjaxUsed":1};
			var porducts = {};
			$.each($('.mass_item'),function(){
				var self = $(this);
				var pid = self.data('product_id');
				var pdata = {};
				$.each(self.find('input,select,textarea'),function(){
					pdata[$(this).attr('name')]=$(this).val();
				});
				porducts[pid]=pdata;
			});
			$.extend(data,{"items":porducts});
			$.post('/cartajax/cartajax/add/',data,function(data){
					
			});
		});
		
	});
})(jQuery);
</script>
















